import { useHistory } from "react-router-dom";
import { DateTime } from "luxon";

import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import CardActionArea from "@mui/material/CardActionArea";

export default function TripHistoryListItem({ trip }) {
  const history = useHistory();

  // format the timestamps generated by the database when the trip was started/ended
  const startDate = DateTime.fromISO(trip.startDate).toLocaleString(
    DateTime.DATE_MED
  );
  const endDate = DateTime.fromISO(trip.endDate).toLocaleString(
    DateTime.DATE_MED
  );

  return (
    <Card sx={{ maxWidth: 345, backgroundColor: "#ededed" }} elevation={3}>
      <CardActionArea onClick={() => history.push(`/history/log/${trip.id}`)}>
        <CardMedia
          component="img"
          width="345"
          image={trip.imagePath}
          alt={trip.parkCode}
        />
        <CardContent sx={{ p: 1 }}>
          <Typography variant="h5" component="h3">
            {trip.fullName ? trip.fullName : trip.name}
          </Typography>
          <Typography variant="body1" componenet="p">
            {startDate} - {endDate}
          </Typography>
        </CardContent>
      </CardActionArea>
      {/* <CardActions sx={{ justifyContent: "flex-end" }}>
        <DeleteButton trip={trip} />
      </CardActions> */}
    </Card>
  );
}
